/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addEvent;

import java.util.Properties;
import javaClass.controller;
import properties.propiedades;

/**
 *
 * @author rodri
 */
public class lockedPrices extends javax.swing.JPanel {

    void verificaridioma()
    {
    Properties pr = new propiedades(controller.idioma);
    lblNotAvaible.setText(pr.getProperty("lblNotAvaible"));
    lblupdatememberlocked.setText(pr.getProperty("lblupdatememberlocked"));
    }
    /**
     * Creates new form lockedPrices
     */
    public lockedPrices() {
        initComponents();
        verificaridioma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNotAvaible = new javax.swing.JLabel();
        lblupdatememberlocked = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(283, 235));
        setMinimumSize(new java.awt.Dimension(283, 235));
        setPreferredSize(new java.awt.Dimension(283, 235));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alert.png"))); // NOI18N

        lblNotAvaible.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNotAvaible.setForeground(new java.awt.Color(255, 51, 51));
        lblNotAvaible.setText("No disponible");

        lblupdatememberlocked.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblupdatememberlocked.setForeground(new java.awt.Color(255, 51, 51));
        lblupdatememberlocked.setText("Actualiza tu membresia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblupdatememberlocked)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNotAvaible)
                            .addGap(29, 29, 29))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNotAvaible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblupdatememberlocked)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNotAvaible;
    private javax.swing.JLabel lblupdatememberlocked;
    // End of variables declaration//GEN-END:variables
}
