package cards;

import javaClass.CheckList;

public class CheckListItem extends javax.swing.JPanel {

    CheckList checkList;
    
    public Runnable onDeleting;
    
    public CheckList getCheckList() {
        checkList.title = txtTitle.getText();
        checkList.checked = jCheckBox1.isSelected();
        return checkList;
    }
    
    public void setCheckList(CheckList checkList) {
        this.checkList = checkList;
        txtTitle.setText(this.checkList.title);
        jCheckBox1.setSelected(this.checkList.checked);
    }
    
    public CheckListItem() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtTitle = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(380, 32));
        setMinimumSize(new java.awt.Dimension(380, 32));
        setPreferredSize(new java.awt.Dimension(380, 32));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(223, 227, 230));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 380, -1));
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 5, -1, -1));

        txtTitle.setAutoscrolls(false);
        txtTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 31));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("X");
        btnDelete.setBorderPainted(false);
        btnDelete.setFocusable(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1, -1, 29));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        onDeleting.run();
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
